modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="99.99"
displayName="Example Mod Eiei"
displayURL="https://www.curseforge.com/members/tannyjung/projects"
logoFile="logo.png"
authors="TannyJung"
description='''A
B
C
D!'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"